// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AuthenticatePlayerArgs {
    pub account_id: u64,
    pub player_name: String,
}

impl From<AuthenticatePlayerArgs> for super::Reducer {
    fn from(args: AuthenticatePlayerArgs) -> Self {
        Self::AuthenticatePlayer {
            account_id: args.account_id,
            player_name: args.player_name,
        }
    }
}

impl __sdk::InModule for AuthenticatePlayerArgs {
    type Module = super::RemoteModule;
}

pub struct AuthenticatePlayerCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `authenticate_player`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait authenticate_player {
    /// Request that the remote module invoke the reducer `authenticate_player` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_authenticate_player`] callbacks.
    fn authenticate_player(&self, account_id: u64, player_name: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `authenticate_player`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AuthenticatePlayerCallbackId`] can be passed to [`Self::remove_on_authenticate_player`]
    /// to cancel the callback.
    fn on_authenticate_player(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &String) + Send + 'static,
    ) -> AuthenticatePlayerCallbackId;
    /// Cancel a callback previously registered by [`Self::on_authenticate_player`],
    /// causing it not to run in the future.
    fn remove_on_authenticate_player(&self, callback: AuthenticatePlayerCallbackId);
}

impl authenticate_player for super::RemoteReducers {
    fn authenticate_player(&self, account_id: u64, player_name: String) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "authenticate_player",
            AuthenticatePlayerArgs {
                account_id,
                player_name,
            },
        )
    }
    fn on_authenticate_player(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &String) + Send + 'static,
    ) -> AuthenticatePlayerCallbackId {
        AuthenticatePlayerCallbackId(self.imp.on_reducer(
            "authenticate_player",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::AuthenticatePlayer {
                                    account_id,
                                    player_name,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, account_id, player_name)
            }),
        ))
    }
    fn remove_on_authenticate_player(&self, callback: AuthenticatePlayerCallbackId) {
        self.imp
            .remove_on_reducer("authenticate_player", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `authenticate_player`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_authenticate_player {
    /// Set the call-reducer flags for the reducer `authenticate_player` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn authenticate_player(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_authenticate_player for super::SetReducerFlags {
    fn authenticate_player(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("authenticate_player", flags);
    }
}
