// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ConnectSessionArgs {
    pub interface_type: String,
    pub connection_id: String,
}

impl From<ConnectSessionArgs> for super::Reducer {
    fn from(args: ConnectSessionArgs) -> Self {
        Self::ConnectSession {
            interface_type: args.interface_type,
            connection_id: args.connection_id,
        }
    }
}

impl __sdk::InModule for ConnectSessionArgs {
    type Module = super::RemoteModule;
}

pub struct ConnectSessionCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `connect_session`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait connect_session {
    /// Request that the remote module invoke the reducer `connect_session` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_connect_session`] callbacks.
    fn connect_session(&self, interface_type: String, connection_id: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `connect_session`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ConnectSessionCallbackId`] can be passed to [`Self::remove_on_connect_session`]
    /// to cancel the callback.
    fn on_connect_session(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> ConnectSessionCallbackId;
    /// Cancel a callback previously registered by [`Self::on_connect_session`],
    /// causing it not to run in the future.
    fn remove_on_connect_session(&self, callback: ConnectSessionCallbackId);
}

impl connect_session for super::RemoteReducers {
    fn connect_session(&self, interface_type: String, connection_id: String) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "connect_session",
            ConnectSessionArgs {
                interface_type,
                connection_id,
            },
        )
    }
    fn on_connect_session(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> ConnectSessionCallbackId {
        ConnectSessionCallbackId(self.imp.on_reducer(
            "connect_session",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::ConnectSession {
                                    interface_type,
                                    connection_id,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, interface_type, connection_id)
            }),
        ))
    }
    fn remove_on_connect_session(&self, callback: ConnectSessionCallbackId) {
        self.imp.remove_on_reducer("connect_session", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `connect_session`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_connect_session {
    /// Set the call-reducer flags for the reducer `connect_session` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn connect_session(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_connect_session for super::SetReducerFlags {
    fn connect_session(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("connect_session", flags);
    }
}
