// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateRoomArgs {
    pub position_x: i32,
    pub position_y: i32,
    pub position_z: i32,
    pub dimension: String,
    pub name: String,
    pub description: String,
    pub exits_json: String,
}

impl From<CreateRoomArgs> for super::Reducer {
    fn from(args: CreateRoomArgs) -> Self {
        Self::CreateRoom {
            position_x: args.position_x,
            position_y: args.position_y,
            position_z: args.position_z,
            dimension: args.dimension,
            name: args.name,
            description: args.description,
            exits_json: args.exits_json,
        }
    }
}

impl __sdk::InModule for CreateRoomArgs {
    type Module = super::RemoteModule;
}

pub struct CreateRoomCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_room`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_room {
    /// Request that the remote module invoke the reducer `create_room` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_room`] callbacks.
    fn create_room(
        &self,
        position_x: i32,
        position_y: i32,
        position_z: i32,
        dimension: String,
        name: String,
        description: String,
        exits_json: String,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_room`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreateRoomCallbackId`] can be passed to [`Self::remove_on_create_room`]
    /// to cancel the callback.
    fn on_create_room(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &i32, &i32, &i32, &String, &String, &String, &String)
            + Send
            + 'static,
    ) -> CreateRoomCallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_room`],
    /// causing it not to run in the future.
    fn remove_on_create_room(&self, callback: CreateRoomCallbackId);
}

impl create_room for super::RemoteReducers {
    fn create_room(
        &self,
        position_x: i32,
        position_y: i32,
        position_z: i32,
        dimension: String,
        name: String,
        description: String,
        exits_json: String,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "create_room",
            CreateRoomArgs {
                position_x,
                position_y,
                position_z,
                dimension,
                name,
                description,
                exits_json,
            },
        )
    }
    fn on_create_room(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &i32, &i32, &i32, &String, &String, &String, &String)
            + Send
            + 'static,
    ) -> CreateRoomCallbackId {
        CreateRoomCallbackId(self.imp.on_reducer(
            "create_room",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::CreateRoom {
                                    position_x,
                                    position_y,
                                    position_z,
                                    dimension,
                                    name,
                                    description,
                                    exits_json,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(
                    ctx,
                    position_x,
                    position_y,
                    position_z,
                    dimension,
                    name,
                    description,
                    exits_json,
                )
            }),
        ))
    }
    fn remove_on_create_room(&self, callback: CreateRoomCallbackId) {
        self.imp.remove_on_reducer("create_room", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_room`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_room {
    /// Set the call-reducer flags for the reducer `create_room` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_room(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_room for super::SetReducerFlags {
    fn create_room(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("create_room", flags);
    }
}
