// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ExecuteTickArgs {}

impl From<ExecuteTickArgs> for super::Reducer {
    fn from(args: ExecuteTickArgs) -> Self {
        Self::ExecuteTick
    }
}

impl __sdk::InModule for ExecuteTickArgs {
    type Module = super::RemoteModule;
}

pub struct ExecuteTickCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `execute_tick`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait execute_tick {
    /// Request that the remote module invoke the reducer `execute_tick` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_execute_tick`] callbacks.
    fn execute_tick(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `execute_tick`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ExecuteTickCallbackId`] can be passed to [`Self::remove_on_execute_tick`]
    /// to cancel the callback.
    fn on_execute_tick(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ExecuteTickCallbackId;
    /// Cancel a callback previously registered by [`Self::on_execute_tick`],
    /// causing it not to run in the future.
    fn remove_on_execute_tick(&self, callback: ExecuteTickCallbackId);
}

impl execute_tick for super::RemoteReducers {
    fn execute_tick(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("execute_tick", ExecuteTickArgs {})
    }
    fn on_execute_tick(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ExecuteTickCallbackId {
        ExecuteTickCallbackId(self.imp.on_reducer(
            "execute_tick",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ExecuteTick {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_execute_tick(&self, callback: ExecuteTickCallbackId) {
        self.imp.remove_on_reducer("execute_tick", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `execute_tick`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_execute_tick {
    /// Set the call-reducer flags for the reducer `execute_tick` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn execute_tick(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_execute_tick for super::SetReducerFlags {
    fn execute_tick(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("execute_tick", flags);
    }
}
