// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GetPlayerInfoArgs {}

impl From<GetPlayerInfoArgs> for super::Reducer {
    fn from(args: GetPlayerInfoArgs) -> Self {
        Self::GetPlayerInfo
    }
}

impl __sdk::InModule for GetPlayerInfoArgs {
    type Module = super::RemoteModule;
}

pub struct GetPlayerInfoCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `get_player_info`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait get_player_info {
    /// Request that the remote module invoke the reducer `get_player_info` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_get_player_info`] callbacks.
    fn get_player_info(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `get_player_info`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`GetPlayerInfoCallbackId`] can be passed to [`Self::remove_on_get_player_info`]
    /// to cancel the callback.
    fn on_get_player_info(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> GetPlayerInfoCallbackId;
    /// Cancel a callback previously registered by [`Self::on_get_player_info`],
    /// causing it not to run in the future.
    fn remove_on_get_player_info(&self, callback: GetPlayerInfoCallbackId);
}

impl get_player_info for super::RemoteReducers {
    fn get_player_info(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("get_player_info", GetPlayerInfoArgs {})
    }
    fn on_get_player_info(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> GetPlayerInfoCallbackId {
        GetPlayerInfoCallbackId(self.imp.on_reducer(
            "get_player_info",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::GetPlayerInfo {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_get_player_info(&self, callback: GetPlayerInfoCallbackId) {
        self.imp.remove_on_reducer("get_player_info", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `get_player_info`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_get_player_info {
    /// Set the call-reducer flags for the reducer `get_player_info` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn get_player_info(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_get_player_info for super::SetReducerFlags {
    fn get_player_info(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("get_player_info", flags);
    }
}
