// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GetCurrentRoomArgs {}

impl From<GetCurrentRoomArgs> for super::Reducer {
    fn from(args: GetCurrentRoomArgs) -> Self {
        Self::GetCurrentRoom
    }
}

impl __sdk::InModule for GetCurrentRoomArgs {
    type Module = super::RemoteModule;
}

pub struct GetCurrentRoomCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `get_current_room`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait get_current_room {
    /// Request that the remote module invoke the reducer `get_current_room` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_get_current_room`] callbacks.
    fn get_current_room(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `get_current_room`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`GetCurrentRoomCallbackId`] can be passed to [`Self::remove_on_get_current_room`]
    /// to cancel the callback.
    fn on_get_current_room(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> GetCurrentRoomCallbackId;
    /// Cancel a callback previously registered by [`Self::on_get_current_room`],
    /// causing it not to run in the future.
    fn remove_on_get_current_room(&self, callback: GetCurrentRoomCallbackId);
}

impl get_current_room for super::RemoteReducers {
    fn get_current_room(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("get_current_room", GetCurrentRoomArgs {})
    }
    fn on_get_current_room(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> GetCurrentRoomCallbackId {
        GetCurrentRoomCallbackId(self.imp.on_reducer(
            "get_current_room",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::GetCurrentRoom {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_get_current_room(&self, callback: GetCurrentRoomCallbackId) {
        self.imp.remove_on_reducer("get_current_room", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `get_current_room`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_get_current_room {
    /// Set the call-reducer flags for the reducer `get_current_room` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn get_current_room(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_get_current_room for super::SetReducerFlags {
    fn get_current_room(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("get_current_room", flags);
    }
}
