// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ListRoomsInDimensionArgs {
    pub dimension: String,
}

impl From<ListRoomsInDimensionArgs> for super::Reducer {
    fn from(args: ListRoomsInDimensionArgs) -> Self {
        Self::ListRoomsInDimension {
            dimension: args.dimension,
        }
    }
}

impl __sdk::InModule for ListRoomsInDimensionArgs {
    type Module = super::RemoteModule;
}

pub struct ListRoomsInDimensionCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `list_rooms_in_dimension`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait list_rooms_in_dimension {
    /// Request that the remote module invoke the reducer `list_rooms_in_dimension` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_list_rooms_in_dimension`] callbacks.
    fn list_rooms_in_dimension(&self, dimension: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `list_rooms_in_dimension`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ListRoomsInDimensionCallbackId`] can be passed to [`Self::remove_on_list_rooms_in_dimension`]
    /// to cancel the callback.
    fn on_list_rooms_in_dimension(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> ListRoomsInDimensionCallbackId;
    /// Cancel a callback previously registered by [`Self::on_list_rooms_in_dimension`],
    /// causing it not to run in the future.
    fn remove_on_list_rooms_in_dimension(&self, callback: ListRoomsInDimensionCallbackId);
}

impl list_rooms_in_dimension for super::RemoteReducers {
    fn list_rooms_in_dimension(&self, dimension: String) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "list_rooms_in_dimension",
            ListRoomsInDimensionArgs { dimension },
        )
    }
    fn on_list_rooms_in_dimension(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> ListRoomsInDimensionCallbackId {
        ListRoomsInDimensionCallbackId(self.imp.on_reducer(
            "list_rooms_in_dimension",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ListRoomsInDimension { dimension },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, dimension)
            }),
        ))
    }
    fn remove_on_list_rooms_in_dimension(&self, callback: ListRoomsInDimensionCallbackId) {
        self.imp
            .remove_on_reducer("list_rooms_in_dimension", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `list_rooms_in_dimension`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_list_rooms_in_dimension {
    /// Set the call-reducer flags for the reducer `list_rooms_in_dimension` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn list_rooms_in_dimension(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_list_rooms_in_dimension for super::SetReducerFlags {
    fn list_rooms_in_dimension(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("list_rooms_in_dimension", flags);
    }
}
