// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct QueuedCommand {
    pub id: u64,
    pub player_id: u64,
    pub session_id: u64,
    pub command: String,
    pub queued_at: u64,
    pub priority: u8,
}

impl __sdk::InModule for QueuedCommand {
    type Module = super::RemoteModule;
}
