// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Room {
    pub id: u64,
    pub position_x: i32,
    pub position_y: i32,
    pub position_z: i32,
    pub dimension: String,
    pub name: String,
    pub description: String,
    pub exits_json: String,
}

impl __sdk::InModule for Room {
    type Module = super::RemoteModule;
}
