// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SubmitCommandArgs {
    pub command_text: String,
}

impl From<SubmitCommandArgs> for super::Reducer {
    fn from(args: SubmitCommandArgs) -> Self {
        Self::SubmitCommand {
            command_text: args.command_text,
        }
    }
}

impl __sdk::InModule for SubmitCommandArgs {
    type Module = super::RemoteModule;
}

pub struct SubmitCommandCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `submit_command`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait submit_command {
    /// Request that the remote module invoke the reducer `submit_command` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_submit_command`] callbacks.
    fn submit_command(&self, command_text: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `submit_command`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SubmitCommandCallbackId`] can be passed to [`Self::remove_on_submit_command`]
    /// to cancel the callback.
    fn on_submit_command(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> SubmitCommandCallbackId;
    /// Cancel a callback previously registered by [`Self::on_submit_command`],
    /// causing it not to run in the future.
    fn remove_on_submit_command(&self, callback: SubmitCommandCallbackId);
}

impl submit_command for super::RemoteReducers {
    fn submit_command(&self, command_text: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("submit_command", SubmitCommandArgs { command_text })
    }
    fn on_submit_command(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> SubmitCommandCallbackId {
        SubmitCommandCallbackId(self.imp.on_reducer(
            "submit_command",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SubmitCommand { command_text },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, command_text)
            }),
        ))
    }
    fn remove_on_submit_command(&self, callback: SubmitCommandCallbackId) {
        self.imp.remove_on_reducer("submit_command", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `submit_command`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_submit_command {
    /// Set the call-reducer flags for the reducer `submit_command` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn submit_command(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_submit_command for super::SetReducerFlags {
    fn submit_command(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("submit_command", flags);
    }
}
